[package]
name = "egui-calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde_json = "1.0.145"
urlencoding = "2.1.3"
